services:
  - type: worker
    name: tg-downloader-bot
    runtime: node
    buildCommand: npm install && apt-get update -qq && apt-get install -y -qq ffmpeg && curl -sL https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && chmod +x /usr/local/bin/yt-dlp
    startCommand: node main/index.js
    envVars:
      - key: NODE_VERSION
        value: 20
